### ISSUE TITLE
Backup didnt work

### ISSUE THREAD

**Issue by joessef102** [Nightkingale/Wii-U-Account-Swap#11]
I was trying to change my nnid email by going into the files but as i did that my mii was removed and my nnid

So i decided to use my backup nnid account but it didnt work.  So i was wondering how do i use the backup?

**Comment by Nightkingale** [comment]
Hey there, thanks for reporting. Can you elaborate exactly what you did? Did you read the README, and are you using the latest version, v2.0.4?

**Comment by joessef102** [comment]
Hi thanks for replying! So i was using ftpii to go i to sysNAND to change my email in the account.dat file but when i did that, it changed my mii and my nnid was gone and made my name to ???. And no i didnt read the README file because i downloaded it from HB app store

**Comment by Nightkingale** [comment]
Oh I see! Yeah, you're not supposed to edit the backups...

They should be left preserved, remember they are system files at the end of the day. I cannot guarantee they still work, The tool only assists the user in moving between a Nintendo and Pretendo one, and I do not recommend any further than that. In fact, I intentionally blocked obviously false `account.dat` files in the latest update.

Hopefully you have a backup before you did the edit. If not, I'm not really sure what to tell you. You should be able to rename your user folder to the old persistent ID, restore the `account.dat`, and edit `common.dat` to match accordingly.

**Comment by joessef102** [comment]
I already did rename the perisistant id to the old one and changed the common.dat and the account.dat

Is there any video or subreddit to see if somebody have the same problem?

**Comment by Nightkingale** [comment]
Not really as far as I know, no. If you want, you can join our [Discord server](https://discord.nightkingale.com) and myself or somebody else can help you out to get your user back. Though since this seems to be user-error, I am going to close the issue.
